"""initial schema

Hand-written (not autogenerated) to be the honest baseline for the schema
that `Base.metadata.create_all()` in app/main.py has been creating all
along — see app/models.py, which this mirrors table-for-table, column-for-
column. Written by hand rather than via `alembic revision --autogenerate`
because every dev/test database in this repo was already built by
create_all before Alembic existed here; autogenerating against one of
those would diff against an already-correct schema and produce an empty
(or misleading) migration. A brand-new empty database — a fresh Postgres
instance on a new deploy — runs this migration to reach exactly the same
schema create_all() would have produced.

Existing databases (local dev SQLite, or any already-deployed Postgres)
should be told they're already at this revision instead of re-running it:
`alembic stamp head` (see backend/README.md's new Alembic section). Only
databases created from nothing should actually execute `upgrade()`.

Revision ID: de4815dad49b
Revises:
Create Date: 2026-09-18 10:50:02.317034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4815dad49b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("fssai_license_number", sa.String(), nullable=True),
        sa.Column("state_code", sa.String(length=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("tier", sa.String(), nullable=True),
        sa.Column("tier_purchased_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "submissions",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("input_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("overall_status", sa.String(), nullable=False),
        sa.Column("has_lab_report", sa.Boolean(), nullable=True),
        sa.Column("batch_lot_number", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_submissions_user_id", "submissions", ["user_id"])

    op.create_table(
        "formulation_iterations",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("product_name", sa.String(), nullable=False),
        sa.Column("iteration_label", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("input_json", sa.JSON(), nullable=False),
        sa.Column("closeness_score", sa.String(), nullable=False),
        sa.Column("gap_summary_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_formulation_iterations_user_id", "formulation_iterations", ["user_id"])

    op.create_table(
        "magic_link_tokens",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("business_name", sa.String(), nullable=True),
        sa.Column("fssai_license_number", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_magic_link_tokens_token_hash", "magic_link_tokens", ["token_hash"], unique=True)
    op.create_index("ix_magic_link_tokens_email", "magic_link_tokens", ["email"])

    op.create_table(
        "leads",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("contact_name", sa.String(), nullable=True),
        sa.Column("contact_email", sa.String(), nullable=False),
        sa.Column("contact_phone", sa.String(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("context_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_leads_user_id", "leads", ["user_id"])


def downgrade() -> None:
    op.drop_index("ix_leads_user_id", table_name="leads")
    op.drop_table("leads")

    op.drop_index("ix_magic_link_tokens_email", table_name="magic_link_tokens")
    op.drop_index("ix_magic_link_tokens_token_hash", table_name="magic_link_tokens")
    op.drop_table("magic_link_tokens")

    op.drop_index("ix_formulation_iterations_user_id", table_name="formulation_iterations")
    op.drop_table("formulation_iterations")

    op.drop_index("ix_submissions_user_id", table_name="submissions")
    op.drop_table("submissions")

    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
