"""
Inspeckt — server-side validation engine (Python port of
frontend/js/validation.js). Kept logically identical to the
frontend engine so a report generated by the API matches one
generated by the browser-only frontend — see README "Two
validation engines".
"""
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from app.dairy_bible import (
    MILK_TYPES, MILK_CROSS_CUTTING, HEAT_TREATMENTS,
    PANEER_TYPES, CHEESE_TYPES, CHEESE_COMMON_RULE,
    MOZZARELLA_FDM_BANDS, MOZZARELLA_FDM_FLOOR, GHEE_TYPES, MILK_POWDER_TYPES, YOGURT_TYPES,
    ICE_CREAM_TYPES, KHOA_TYPES, FLAVOURED_MILK_TYPES, EVAPORATED_MILK_TYPES,
    SWEETENED_CONDENSED_MILK_TYPES, CREAM_TYPES, DAIRY_WHITENER_TYPES,
    WHEY_POWDER_TYPES, CASEIN_PRODUCTS_TYPES, EDIBLE_LACTOSE_TYPES,
    MILK_PROTEIN_CONCENTRATE_TYPES, WHEY_PROTEIN_CONCENTRATE_TYPES, COLOSTRUM_PRODUCTS_TYPES,
    DAIRY_PERMEATE_POWDERS_TYPES,
    MICRO_LIMITS, LABEL_ELEMENTS_ALL, LABEL_ELEMENTS_BY_CATEGORY,
    REPORT_DISCLAIMER,
)

SEVERITY_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}


def _check(label, status, actual, expected, ref, severity):
    return {"label": label, "status": status, "actual": actual, "expected": expected, "ref": ref, "severity": severity}


def _check_min(label, value, minimum, unit, ref, severity="CRITICAL"):
    if value is None:
        return _check(label, "MISSING", "—", f"≥ {minimum}{unit}", ref, severity)
    passed = value >= minimum
    return _check(label, "PASS" if passed else "FAIL", f"{value}{unit}", f"≥ {minimum}{unit}", ref, severity)


def _check_max(label, value, maximum, unit, ref, severity="HIGH"):
    if value is None:
        return _check(label, "MISSING", "—", f"≤ {maximum}{unit}", ref, severity)
    passed = value <= maximum
    return _check(label, "PASS" if passed else "FAIL", f"{value}{unit}", f"≤ {maximum}{unit}", ref, severity)


def _check_between(label, value, minimum, maximum, unit, ref, severity="CRITICAL"):
    if value is None:
        return _check(label, "MISSING", "—", f"{minimum}–{maximum}{unit}", ref, severity)
    passed = minimum <= value <= maximum
    return _check(label, "PASS" if passed else "FAIL", f"{value}{unit}", f"{minimum}–{maximum}{unit}", ref, severity)


def _title_case(s):
    s = str(s).strip()
    return s[:1].upper() + s[1:].lower() if s else s


def _check_equals(label, value, expected, ref, severity="CRITICAL"):
    """Fix per review item C17 (Ghee/Butter): a categorical/pass-fail lab
    result (Baudouin Test, presence of β-sitosterol) rather than a numeric
    threshold — mirrors validation.js's checkEquals(). Comparison is
    case-insensitive so "Negative"/"negative" both match the UI's
    lowercase select values."""
    expected_text = _title_case(expected)
    if value is None or value == "":
        return _check(label, "MISSING", "—", expected_text, ref, severity)
    passed = str(value).strip().lower() == str(expected).strip().lower()
    return _check(label, "PASS" if passed else "FAIL", _title_case(value), expected_text, ref, severity)


def _check_micro_count(name, value, limit, ref):
    unit = limit["unit"]
    if value is None:
        return _check(f"{name} ({unit})", "MISSING", "—", f"≤ {limit['m']}", ref, "HIGH")
    if value <= limit["m"]:
        return _check(f"{name} ({unit})", "PASS", value, f"≤ {limit['m']} (m)", ref, "HIGH")
    if limit["M"] is not None and value <= limit["M"]:
        return _check(f"{name} ({unit})", "WARNING", value,
                       f"≤ {limit['m']} (m) — between acceptable ({limit['m']}) and rejection ({limit['M']}) limit",
                       ref, "HIGH")
    # Fix per review item B1 — sign-off received (escalate to CRITICAL):
    # mirrors the JS engine's fix. A confirmed breach is CRITICAL
    # regardless of whether the organism uses a 2-class (ceiling only) or
    # 3-class (warning band + rejection limit) sampling plan — a HIGH
    # severity here used to let a single confirmed E. coli/Staph aureus
    # result over the limit render as WARNING instead of FAIL.
    expected = f"≤ {limit['M']} (M, rejection limit)" if limit["M"] is not None else f"≤ {limit['m']}"
    return _check(f"{name} ({unit})", "FAIL", value, expected, ref, "CRITICAL")


def _check_micro_presence(name, detected, limit, ref):
    if detected is None:
        return _check(name, "MISSING", "—", f"Absent {limit['unit']}", ref, "CRITICAL")
    return _check(name, "FAIL" if detected else "PASS", "Detected" if detected else "Absent",
                   f"Absent {limit['unit']}", ref, "CRITICAL")


def _run_microbiology(category_id: str, lab: Dict[str, Any]) -> Optional[List[dict]]:
    """Fix per review item C17 (bring not-live categories live,
    composition-only): returns None — not an empty list — when this
    category has no MICRO_LIMITS entry yet, mirroring validation.js's
    runMicrobiology(). Lets validate_submission() below tell "no panel
    exists" apart from "the panel exists and everything passed."""
    limits = MICRO_LIMITS.get(category_id)
    if not limits:
        return None
    checks = []
    # Routes by each entry's own "presence" flag, not by table section —
    # mirrors validation.js's runMicrobiology(). Ghee/Butter (Sr.6) and
    # Yogurt/Dahi (Sr.12) list E. coli in Table 2A as "Absent/g", a
    # presence/absence test, not a CFU count with an m/M band.
    for key, limit in limits["table_2a"].items():
        checker = _check_micro_presence if limit.get("presence") else _check_micro_count
        checks.append(checker(limit["name"], lab.get(key), limit, "Appendix B, Table 2A"))
    # Same presence-vs-count routing as Table 2A above — found while
    # smoke-testing the new Dried Ice Cream Mix sub-types (which share
    # Milk Powder's Sr.7 bucket): Milk Powder's own Table 2B carries
    # Bacillus cereus and Sulphite Reducing Clostridia as real CFU counts
    # with m/M bands (500/1000 and 50/100), not presence/absence tests
    # like Salmonella/Listeria — but this loop was running every Table 2B
    # entry through the presence checker unconditionally, so a real count
    # like "400 CFU/g" (well under the 500 acceptable limit) was being
    # read as "Detected" and forced to FAIL. Pre-existing bug in the
    # already-live Milk Powder category, not something introduced by Ice
    # Cream — fixed here since Dried Ice Cream Mix inherits the same bucket.
    for key, limit in limits["table_2b"].items():
        checker = _check_micro_presence if limit.get("presence") else _check_micro_count
        checks.append(checker(limit["name"], lab.get(key), limit, "Appendix B, Table 2B"))
    return checks


def _run_labelling(category_id: str, label: Dict[str, Any]) -> List[dict]:
    """Same cross-engine parity fix as _aggregate_status()/_section_status()
    above: an unticked label element used to be graded "FAIL" outright,
    with no MISSING state at all — unlike validation.js's runLabelling(),
    whose comment is explicit that a checkbox left unticked means "not yet
    declared," not "wrong" (very normal for a product still being
    formulated, before packaging artwork exists). Now MISSING here too, so
    a half-finished label checklist gets the same honest "still some
    things to finish" verdict from either engine. `elements` is looked up
    generically from LABEL_ELEMENTS_ALL/LABEL_ELEMENTS_BY_CATEGORY by
    category_id, so this is unchanged for every category, live or future."""
    elements = LABEL_ELEMENTS_ALL + LABEL_ELEMENTS_BY_CATEGORY.get(category_id, [])
    checks = []
    for el in elements:
        declared = bool(label.get(el["key"]))
        checks.append(_check(el["label"], "PASS" if declared else "MISSING",
                              "Declared" if declared else "Not yet declared", "Declared",
                              "Labelling & Display Regs 2020", el["severity"]))
    return checks


def _run_milk_composition(inp: Dict[str, Any]) -> List[dict]:
    spec = MILK_TYPES.get(inp.get("milk_type"))
    if not spec:
        return []
    checks = []
    # Fix mirroring the JS engine's skimmed-milk fix (D1 / the frontend
    # engine's "the skimmed-milk fix" note in dairyBible.js): this used
    # to add a *second*, redundant "Milk Fat max" check whenever
    # min_fat == 0, on top of the _check_between check just above it —
    # double-counting the same constraint (worse, at a different default
    # severity: HIGH from the duplicate vs CRITICAL from the between
    # check) in both the report and the Formulation Lab's severity-
    # weighted score. The `between` check already covers a 0-to-max
    # range correctly on its own; the extra branch was never needed.
    # This bug was already fixed on the JS side in an earlier pass —
    # the Python engine had drifted and still had it.
    if "max_fat" in spec:
        checks.append(_check_between(f"Milk Fat ({spec['name']})", inp.get("fat"), spec["min_fat"], spec["max_fat"], "%", spec["ref"]))
    else:
        checks.append(_check_min(f"Milk Fat ({spec['name']})", inp.get("fat"), spec["min_fat"], "%", spec["ref"]))
    checks.append(_check_min("SNF (Solids-Not-Fat)", inp.get("snf"), spec["min_snf"], "%", spec["ref"]))

    sodium = inp.get("sodium")
    if sodium is not None:
        checks.append(_check_max("Sodium", sodium, MILK_CROSS_CUTTING["max_sodium_mg_per_100g_snf"]["value"],
                                  " mg/100g SNF", MILK_CROSS_CUTTING["max_sodium_mg_per_100g_snf"]["ref"], "HIGH"))
    urea = inp.get("urea")
    if urea is not None:
        checks.append(_check_max("Urea", urea, MILK_CROSS_CUTTING["max_urea_ppm"]["value"],
                                  " ppm", MILK_CROSS_CUTTING["max_urea_ppm"]["ref"], "MEDIUM"))
    return checks


def _run_paneer_composition(inp: Dict[str, Any]) -> List[dict]:
    spec = PANEER_TYPES.get(inp.get("paneer_type"))
    if not spec:
        return []
    checks = [_check_max(f"Moisture ({spec['name']})", inp.get("moisture"), spec["max_moisture"], "%", spec["ref"], "HIGH")]
    if "max_fat_dry" in spec and "min_fat_dry" in spec:
        checks.append(_check_between("Milk Fat (dry basis)", inp.get("fat"), spec["min_fat_dry"], spec["max_fat_dry"], "%", spec["ref"]))
    elif "max_fat_dry" in spec:
        checks.append(_check_max("Milk Fat (dry basis)", inp.get("fat"), spec["max_fat_dry"], "%", spec["ref"]))
    else:
        checks.append(_check_min("Milk Fat (dry basis)", inp.get("fat"), spec["min_fat_dry"], "%", spec["ref"]))
    return checks


def _run_mozzarella_composition(spec: Dict[str, Any], inp: Dict[str, Any]) -> List[dict]:
    """Fix per review item C17 follow-up — mirrors validation.js's
    runMozzarellaComposition(). See the "computed" comment on
    CHEESE_TYPES["mozzarella"] in dairy_bible.py for the source table."""
    raw_fat = inp.get("fat")
    raw_moisture = inp.get("moisture")
    moisture_type = "high_moisture" if inp.get("moisture_type") == "high_moisture" else "low_moisture"
    type_label = "High moisture" if moisture_type == "high_moisture" else "Low moisture"
    floor = MOZZARELLA_FDM_FLOOR[moisture_type]

    if raw_fat is None or raw_moisture is None or raw_moisture >= 100:
        return [
            _check("Fat in Dry Matter (FDM)", "MISSING", "—", f"≥ {floor}% FDM ({type_label} Mozzarella)", spec["ref"], "CRITICAL"),
            _check("Moisture (Mozzarella)", "MISSING", "—", "Depends on the FDM band — enter Milk Fat and Moisture to see it", spec["ref"], "HIGH"),
        ]

    fat = float(raw_fat)
    moisture = float(raw_moisture)
    fdm = (fat / (100 - moisture)) * 100

    floor_check = _check("Fat in Dry Matter (FDM)", "PASS" if fdm >= floor else "FAIL",
                          f"{fdm:.1f}%", f"≥ {floor}% FDM ({type_label} Mozzarella)", spec["ref"], "CRITICAL")

    band = next((b for b in MOZZARELLA_FDM_BANDS if b["min_fdm"] <= fdm < b["max_fdm"]), None)
    if band is None:
        return [floor_check, _check(
            "Moisture (Mozzarella)", "MISSING", f"{moisture}%",
            "FDM is outside the Compositional Standards Table-2 range (18–85%) — double-check the entered fat/moisture",
            spec["ref"], "HIGH",
        )]
    min_dry_matter = band["high_dm"] if moisture_type == "high_moisture" else band["low_dm"]
    max_moisture = 100 - min_dry_matter
    qualifier_note = f" — {band['qualifier']} classification" if band["qualifier"] else ""
    moisture_check = _check(
        "Moisture (Mozzarella)", "PASS" if moisture <= max_moisture else "FAIL",
        f"{moisture}%", f"≤ {max_moisture:.1f}% (min dry matter {min_dry_matter}%{qualifier_note})",
        spec["ref"], "HIGH",
    )
    return [floor_check, moisture_check]


def _run_cheese_composition(inp: Dict[str, Any]) -> List[dict]:
    spec = CHEESE_TYPES.get(inp.get("cheese_type"))
    if not spec:
        return []
    if spec.get("computed") == "mozzarella_fdm":
        return _run_mozzarella_composition(spec, inp)
    checks = [_check_max(f"Moisture ({spec['name']})", inp.get("moisture"), spec["max_moisture"], "%", spec["ref"], "HIGH")]
    basis_label = "Milk Fat (dry basis)" if spec["fat_basis"] == "dry" else "Milk Fat (as-is basis)"
    checks.append(_check_min(basis_label, inp.get("fat"), spec["min_fat"], "%", spec["ref"]))
    # Fix per review item C17 follow-up: `max_lactose` is back for
    # Processed Cheese — see the CHEESE_TYPES comment in dairy_bible.py.
    # Optional: only added to the report when the FBO actually entered a
    # value, mirroring milk's sodium/urea treatment.
    lactose = inp.get("lactose")
    if "max_lactose" in spec and lactose is not None:
        checks.append(_check_max("Lactose", lactose, spec["max_lactose"], "%", spec.get("lactose_ref", spec["ref"]), "MEDIUM"))
    return checks


def _run_fields(fields: List[dict], spec_name: str, inp: Dict[str, Any]) -> List[dict]:
    """Fix per review item C17 (bring not-live categories live,
    composition-only): generic walker over an explicit fields list —
    mirrors validation.js's runFields()/runFieldCheck(). Extracted out of
    _run_generic_field_composition() (which walks a whole *_TYPES[...]
    entry's fields) so _run_milk_cross_reference_composition() below can
    also call it directly on a partial fields list (Plain Dahi's own
    protein/acidity fields, plus a second call for the milk-cross-
    referenced fat/snf fields) without a second copy of this loop."""
    checks = []
    for field in fields:
        raw = inp.get(field["key"])
        present = raw is not None and raw != ""
        # Optional fields (Ghee's quality-factor tests, milk powder's
        # sodium note) that were never answered don't produce a row at
        # all — same treatment as milk's sodium/urea and cheese's
        # lactose. Required fields always produce a row (MISSING if
        # unanswered).
        if field.get("optional") and not present:
            continue
        label = field["report_label"].replace("{name}", spec_name)
        if field["rule"] == "equals":
            value = raw if present else None
        else:
            value = float(raw) if present else None
        if field["rule"] == "min":
            checks.append(_check_min(label, value, field["min"], field["unit"], field["ref"], field["severity"]))
        elif field["rule"] == "max":
            checks.append(_check_max(label, value, field["max"], field["unit"], field["ref"], field["severity"]))
        elif field["rule"] == "equals":
            checks.append(_check_equals(label, value, field["equals"], field["ref"], field["severity"]))
        else:
            checks.append(_check_between(label, value, field["min"], field["max"], field["unit"], field["ref"], field["severity"]))
    return checks


def _run_generic_field_composition(type_table: Dict[str, Any], subtype_key: str, inp: Dict[str, Any]) -> List[dict]:
    """Whole-schema walk: looks up the matched sub-type's own `fields`
    list and runs it through _run_fields(). Shared by Ghee/Butter, Milk
    Powder, and every ordinary Yogurt/Dahi sub-type (see the long comment
    on GHEE_TYPES in dairy_bible.py for why these categories use a
    generic field list instead of the flat, hand-written keys every
    older *_composition function in this file reads)."""
    spec = type_table.get(inp.get(subtype_key))
    if not spec:
        return []
    return _run_fields(spec["fields"], spec["name"], inp)


def _run_ghee_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(GHEE_TYPES, "ghee_type", inp)


def _run_milk_powder_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(MILK_POWDER_TYPES, "milk_powder_type", inp)


def _run_milk_cross_reference_composition(spec: Dict[str, Any], inp: Dict[str, Any]) -> List[dict]:
    """Renamed from _run_dahi_composition() when Flavoured Milk (FSS
    2.1.3, Item 2(c)) turned out to need the exact same mechanism as
    Plain Dahi (FSS 2.1.13, Item 2(c)(iii)) — both regulations say the
    product's own Milk Fat/SNF minimums ARE whichever milk it's made
    from, so both reuse MILK_TYPES's already-sourced numbers (this
    file's flat "min_fat"/"max_fat"/"min_snf" keys, not a `fields` list
    — see the YOGURT_TYPES comment in dairy_bible.py for that shape
    divergence) instead of duplicating them, per your "cross-reference
    Milk live" sign-off. Mirrors validation.js's
    runMilkCrossReferenceComposition() (itself renamed from
    runDahiComposition()). The function body is unchanged from the
    Dahi-only version — it was already fully generic — only the name and
    the MISSING-case wording changed. Plain Dahi additionally has its own
    Fermented Milk protein/acidity minimums (Item 2(c)(ii)) as ordinary
    `fields`, run through _run_fields() first; Flavoured Milk's `fields`
    list is empty (FSS 2.1.3, Item 2 states no other composition
    requirement), so that call is a no-op for it."""
    general_checks = _run_fields(spec["fields"], spec["name"], inp)
    milk_spec = MILK_TYPES.get(inp.get("milk_type"))
    if not milk_spec:
        return general_checks + [
            _check("Milk Fat (same as source milk)", "MISSING", "—", "Select which milk this product was made from", spec["ref"], "CRITICAL"),
            _check("SNF (same as source milk)", "MISSING", "—", "Select which milk this product was made from", spec["ref"], "CRITICAL"),
        ]
    raw_fat = inp.get("fat")
    fat_value = float(raw_fat) if raw_fat is not None and raw_fat != "" else None
    if "max_fat" in milk_spec:
        milk_checks = [_check_between(f"Milk Fat ({milk_spec['name']})", fat_value, milk_spec["min_fat"], milk_spec["max_fat"], "%", milk_spec["ref"])]
    else:
        milk_checks = [_check_min(f"Milk Fat ({milk_spec['name']})", fat_value, milk_spec["min_fat"], "%", milk_spec["ref"])]
    raw_snf = inp.get("snf")
    snf_value = float(raw_snf) if raw_snf is not None and raw_snf != "" else None
    milk_checks.append(_check_min("SNF (Solids-Not-Fat)", snf_value, milk_spec["min_snf"], "%", milk_spec["ref"]))
    return general_checks + milk_checks


def _run_yogurt_composition(inp: Dict[str, Any]) -> List[dict]:
    spec = YOGURT_TYPES.get(inp.get("yogurt_type"))
    if not spec:
        return []
    if spec.get("computed") == "milk_cross_reference":
        return _run_milk_cross_reference_composition(spec, inp)
    return _run_generic_field_composition(YOGURT_TYPES, "yogurt_type", inp)


def _run_ice_cream_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(ICE_CREAM_TYPES, "ice_cream_type", inp)


def _run_khoa_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(KHOA_TYPES, "khoa_type", inp)


def _run_flavoured_milk_composition(inp: Dict[str, Any]) -> List[dict]:
    """Mirrors _run_yogurt_composition()'s internal dispatch for Plain
    Dahi: Flavoured Milk's one sub-type always carries
    `"computed": "milk_cross_reference"` (see FLAVOURED_MILK_TYPES in
    dairy_bible.py), so this wrapper always takes that branch — there is
    no non-cross-referenced fallback for this category the way ordinary
    Yogurt/Dahi sub-types have one."""
    spec = FLAVOURED_MILK_TYPES.get(inp.get("flavoured_milk_type"))
    if not spec:
        return []
    if spec.get("computed") == "milk_cross_reference":
        return _run_milk_cross_reference_composition(spec, inp)
    return _run_generic_field_composition(FLAVOURED_MILK_TYPES, "flavoured_milk_type", inp)


def _run_evaporated_milk_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(EVAPORATED_MILK_TYPES, "evaporated_milk_type", inp)


def _run_sweetened_condensed_milk_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(SWEETENED_CONDENSED_MILK_TYPES, "sweetened_condensed_milk_type", inp)


def _run_cream_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(CREAM_TYPES, "cream_type", inp)


def _run_dairy_whitener_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(DAIRY_WHITENER_TYPES, "dairy_whitener_type", inp)


def _run_whey_powder_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(WHEY_POWDER_TYPES, "whey_powder_type", inp)


def _run_casein_products_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(CASEIN_PRODUCTS_TYPES, "casein_products_type", inp)


def _run_edible_lactose_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(EDIBLE_LACTOSE_TYPES, "edible_lactose_type", inp)


def _run_milk_protein_concentrate_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(MILK_PROTEIN_CONCENTRATE_TYPES, "milk_protein_concentrate_type", inp)


def _run_whey_protein_concentrate_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(WHEY_PROTEIN_CONCENTRATE_TYPES, "whey_protein_concentrate_type", inp)


def _run_colostrum_products_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(COLOSTRUM_PRODUCTS_TYPES, "colostrum_products_type", inp)


def _run_dairy_permeate_powders_composition(inp: Dict[str, Any]) -> List[dict]:
    return _run_generic_field_composition(DAIRY_PERMEATE_POWDERS_TYPES, "dairy_permeate_powders_type", inp)


def _shelf_life(category_id: str, inp: Dict[str, Any]) -> Dict[str, Any]:
    if category_id == "milk":
        ht = HEAT_TREATMENTS.get(inp.get("heat_treatment"))
        if not ht:
            return {"days": None, "storage_temp": "—", "note": "Select a heat treatment to estimate shelf life."}
        return {"days": ht["shelf_days"], "storage_temp": ht["storage_temp"], "note": None}
    if category_id == "paneer":
        return {"days": 7, "storage_temp": "2-6°C", "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "cheese":
        spec = CHEESE_TYPES.get(inp.get("cheese_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "ghee":
        spec = GHEE_TYPES.get(inp.get("ghee_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "milk_powder":
        spec = MILK_POWDER_TYPES.get(inp.get("milk_powder_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "yogurt":
        spec = YOGURT_TYPES.get(inp.get("yogurt_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "ice_cream":
        spec = ICE_CREAM_TYPES.get(inp.get("ice_cream_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "khoa":
        spec = KHOA_TYPES.get(inp.get("khoa_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "flavoured_milk":
        spec = FLAVOURED_MILK_TYPES.get(inp.get("flavoured_milk_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "evaporated_milk":
        spec = EVAPORATED_MILK_TYPES.get(inp.get("evaporated_milk_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "sweetened_condensed_milk":
        spec = SWEETENED_CONDENSED_MILK_TYPES.get(inp.get("sweetened_condensed_milk_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "cream":
        spec = CREAM_TYPES.get(inp.get("cream_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "dairy_whitener":
        spec = DAIRY_WHITENER_TYPES.get(inp.get("dairy_whitener_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "whey_powder":
        spec = WHEY_POWDER_TYPES.get(inp.get("whey_powder_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "casein_products":
        spec = CASEIN_PRODUCTS_TYPES.get(inp.get("casein_products_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "edible_lactose":
        spec = EDIBLE_LACTOSE_TYPES.get(inp.get("edible_lactose_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "milk_protein_concentrate":
        spec = MILK_PROTEIN_CONCENTRATE_TYPES.get(inp.get("milk_protein_concentrate_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "whey_protein_concentrate":
        spec = WHEY_PROTEIN_CONCENTRATE_TYPES.get(inp.get("whey_protein_concentrate_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "colostrum_products":
        spec = COLOSTRUM_PRODUCTS_TYPES.get(inp.get("colostrum_products_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    if category_id == "dairy_permeate_powders":
        spec = DAIRY_PERMEATE_POWDERS_TYPES.get(inp.get("dairy_permeate_powders_type"))
        if not spec:
            return {"days": None, "storage_temp": "—", "note": None}
        return {"days": spec["shelf_days"], "storage_temp": spec["storage_temp"],
                "note": "Estimated — confirm with your own shelf-life study."}
    return {"days": None, "storage_temp": "—", "note": None}


# Fix per the cross-engine parity review (checks/check-engine-parity.mjs):
# this used to escalate a MISSING check straight to FAIL whenever its
# severity was CRITICAL — e.g. an unfinished submission with a required
# lab field not yet entered. That directly contradicted this engine's own
# frontend counterpart, validation.js's aggregateStatus(), whose comment
# is explicit about why: "FAIL is reserved for something that was
# actually tested/declared and came back non-compliant. A MISSING check
# — a lab test not yet run, a label element not yet finalized — means
# 'not done yet,' not 'wrong.'" Identical input used to produce a yellow
# "Warning — still some things to finish" in the browser and a red "FAIL
# / release blocked" from this same function on the API side. Rewritten
# to match validation.js's aggregateStatus() exactly: MISSING (at any
# severity) escalates only as far as WARNING, never FAIL, on its own.
# Driven entirely by each check's `status`/`severity` fields — no
# category id appears here — so this applies unchanged to every category,
# live today or added later.
def _aggregate_status(all_checks: List[dict]) -> str:
    failed = [c for c in all_checks if c["status"] == "FAIL"]
    missing = [c for c in all_checks if c["status"] == "MISSING"]
    critical_failures = [c for c in failed if c["severity"] == "CRITICAL"]
    high_failures = [c for c in failed if c["severity"] == "HIGH"]
    if critical_failures or len(high_failures) >= 3:
        return "FAIL"
    if high_failures or missing or any(c["status"] == "WARNING" for c in all_checks):
        return "WARNING"
    return "PASS"


# Same fix, section-level: mirrors validation.js's sectionStatus() exactly
# now — a MISSING check (any severity) caps a section at WARNING, never
# forces it to FAIL. Also category-agnostic by construction.
def _section_status(checks: List[dict]) -> str:
    if any(c["status"] == "FAIL" for c in checks):
        return "FAIL"
    if any(c["status"] in ("WARNING", "MISSING") for c in checks):
        return "WARNING"
    return "PASS"


_SCORE_WEIGHT = {"CRITICAL": 3, "HIGH": 2, "MEDIUM": 1, "LOW": 1}


def score_formulation(category_id: str, inp: Dict[str, Any]) -> Dict[str, Any]:
    """Formulation Lab scoring: how close a *planned* formulation is to
    compliant, using only the numbers the FBO has entered themselves — no
    lab report exists yet at this stage, so only composition checks run
    (microbiology and label checks need real test/label data and are not
    part of a pre-lab formulation draft). See PLATFORM_PLAN_V2.md §2.5.

    Returns a 0-100 closeness score (severity-weighted pass rate) and a
    gap summary of what's failing or still missing, so a user comparing
    iterations can see exactly what to change.
    """
    if category_id == "milk":
        checks = _run_milk_composition(inp)
    elif category_id == "paneer":
        checks = _run_paneer_composition(inp)
    elif category_id == "cheese":
        checks = _run_cheese_composition(inp)
    elif category_id == "ghee":
        checks = _run_ghee_composition(inp)
    elif category_id == "milk_powder":
        checks = _run_milk_powder_composition(inp)
    elif category_id == "yogurt":
        checks = _run_yogurt_composition(inp)
    elif category_id == "ice_cream":
        checks = _run_ice_cream_composition(inp)
    elif category_id == "khoa":
        checks = _run_khoa_composition(inp)
    elif category_id == "flavoured_milk":
        checks = _run_flavoured_milk_composition(inp)
    elif category_id == "evaporated_milk":
        checks = _run_evaporated_milk_composition(inp)
    elif category_id == "sweetened_condensed_milk":
        checks = _run_sweetened_condensed_milk_composition(inp)
    elif category_id == "cream":
        checks = _run_cream_composition(inp)
    elif category_id == "dairy_whitener":
        checks = _run_dairy_whitener_composition(inp)
    elif category_id == "whey_powder":
        checks = _run_whey_powder_composition(inp)
    elif category_id == "casein_products":
        checks = _run_casein_products_composition(inp)
    elif category_id == "edible_lactose":
        checks = _run_edible_lactose_composition(inp)
    elif category_id == "milk_protein_concentrate":
        checks = _run_milk_protein_concentrate_composition(inp)
    elif category_id == "whey_protein_concentrate":
        checks = _run_whey_protein_concentrate_composition(inp)
    elif category_id == "colostrum_products":
        checks = _run_colostrum_products_composition(inp)
    elif category_id == "dairy_permeate_powders":
        checks = _run_dairy_permeate_powders_composition(inp)
    else:
        checks = []

    if not checks:
        return {"score": 0, "gap_summary": [{"label": "Product type", "issue": "Select a valid product sub-type to score this iteration."}]}

    total_weight = sum(_SCORE_WEIGHT.get(c["severity"], 1) for c in checks)
    passed_weight = sum(_SCORE_WEIGHT.get(c["severity"], 1) for c in checks if c["status"] == "PASS")
    score = round((passed_weight / total_weight) * 100) if total_weight else 0

    gap_summary = [
        {"label": c["label"], "issue": f"{c['actual']} — needs {c['expected']}", "severity": c["severity"], "ref": c["ref"]}
        for c in checks
        if c["status"] != "PASS"
    ]
    return {"score": score, "gap_summary": gap_summary}


def validate_submission(category_id: str, inp: Dict[str, Any], has_lab_report: bool = False) -> Dict[str, Any]:
    """`has_lab_report` gates anything that would otherwise require a
    fabricated number: the populated nutrition panel and claims validation
    both require a real, uploaded NABL test report — see
    PLATFORM_PLAN_V2.md §2.6, "no fabrication" rule. Composition and label-
    structure checks still run either way, since those come from the FBO's
    own entered numbers and declarations, not from a lab."""
    if category_id == "milk":
        composition = _run_milk_composition(inp)
    elif category_id == "paneer":
        composition = _run_paneer_composition(inp)
    elif category_id == "cheese":
        composition = _run_cheese_composition(inp)
    elif category_id == "ghee":
        composition = _run_ghee_composition(inp)
    elif category_id == "milk_powder":
        composition = _run_milk_powder_composition(inp)
    elif category_id == "yogurt":
        composition = _run_yogurt_composition(inp)
    elif category_id == "ice_cream":
        composition = _run_ice_cream_composition(inp)
    elif category_id == "khoa":
        composition = _run_khoa_composition(inp)
    elif category_id == "flavoured_milk":
        composition = _run_flavoured_milk_composition(inp)
    elif category_id == "evaporated_milk":
        composition = _run_evaporated_milk_composition(inp)
    elif category_id == "sweetened_condensed_milk":
        composition = _run_sweetened_condensed_milk_composition(inp)
    elif category_id == "cream":
        composition = _run_cream_composition(inp)
    elif category_id == "dairy_whitener":
        composition = _run_dairy_whitener_composition(inp)
    elif category_id == "whey_powder":
        composition = _run_whey_powder_composition(inp)
    elif category_id == "casein_products":
        composition = _run_casein_products_composition(inp)
    elif category_id == "edible_lactose":
        composition = _run_edible_lactose_composition(inp)
    elif category_id == "milk_protein_concentrate":
        composition = _run_milk_protein_concentrate_composition(inp)
    elif category_id == "whey_protein_concentrate":
        composition = _run_whey_protein_concentrate_composition(inp)
    elif category_id == "colostrum_products":
        composition = _run_colostrum_products_composition(inp)
    elif category_id == "dairy_permeate_powders":
        composition = _run_dairy_permeate_powders_composition(inp)
    else:
        composition = []

    # Mirrors validation.js's specFor()-driven microKey resolution: most
    # sub-types check against MICRO_LIMITS[category_id] directly, but a
    # sub-type can declare its own "micro_key" (see CHEESE_TYPES
    # ["processed_cheese"]) to be checked against a different, stricter
    # panel — Part II Ch 6.2's Processed Cheese/Cheese Spread exception.
    sub_type_key = {
        "milk": "milk_type", "paneer": "paneer_type", "cheese": "cheese_type",
        "ghee": "ghee_type", "milk_powder": "milk_powder_type", "yogurt": "yogurt_type",
        "ice_cream": "ice_cream_type", "khoa": "khoa_type",
        "flavoured_milk": "flavoured_milk_type", "evaporated_milk": "evaporated_milk_type",
        "sweetened_condensed_milk": "sweetened_condensed_milk_type", "cream": "cream_type",
        "dairy_whitener": "dairy_whitener_type", "whey_powder": "whey_powder_type",
        "casein_products": "casein_products_type", "edible_lactose": "edible_lactose_type",
        "milk_protein_concentrate": "milk_protein_concentrate_type",
        "whey_protein_concentrate": "whey_protein_concentrate_type",
        "colostrum_products": "colostrum_products_type",
        "dairy_permeate_powders": "dairy_permeate_powders_type",
    }.get(category_id)
    spec_table = {
        "milk": MILK_TYPES, "paneer": PANEER_TYPES, "cheese": CHEESE_TYPES,
        "ghee": GHEE_TYPES, "milk_powder": MILK_POWDER_TYPES, "yogurt": YOGURT_TYPES,
        "ice_cream": ICE_CREAM_TYPES, "khoa": KHOA_TYPES,
        "flavoured_milk": FLAVOURED_MILK_TYPES, "evaporated_milk": EVAPORATED_MILK_TYPES,
        "sweetened_condensed_milk": SWEETENED_CONDENSED_MILK_TYPES, "cream": CREAM_TYPES,
        "dairy_whitener": DAIRY_WHITENER_TYPES, "whey_powder": WHEY_POWDER_TYPES,
        "casein_products": CASEIN_PRODUCTS_TYPES, "edible_lactose": EDIBLE_LACTOSE_TYPES,
        "milk_protein_concentrate": MILK_PROTEIN_CONCENTRATE_TYPES,
        "whey_protein_concentrate": WHEY_PROTEIN_CONCENTRATE_TYPES,
        "colostrum_products": COLOSTRUM_PRODUCTS_TYPES,
        "dairy_permeate_powders": DAIRY_PERMEATE_POWDERS_TYPES,
    }.get(category_id)
    spec = spec_table.get(inp.get(sub_type_key)) if spec_table and sub_type_key else None
    micro_category_id = (spec or {}).get("micro_key", category_id)
    # Fix per review item C17: None (not []) means no microbiology panel
    # is compiled for this category yet — see _run_microbiology()'s own
    # comment above.
    micro_raw = _run_microbiology(micro_category_id, inp.get("lab") or {})
    micro_available = micro_raw is not None
    micro = micro_raw if micro_available else []
    label = _run_labelling(category_id, inp.get("label") or {})
    shelf_life = _shelf_life(category_id, inp)

    if has_lab_report:
        nutrition_panel = {"status": "AVAILABLE", "note": "Populated from the uploaded NABL lab report."}
        claims = {
            "status": "NOT_YET_IMPLEMENTED",
            "checks": [],
            "note": (
                "Claims validation (Schedule I thresholds, prohibited claims) is not yet built into this "
                "engine — the lab report requirement is enforced, but the check itself needs the "
                "Advertising & Claims regulatory data compiled and signed off first."
            ),
        }
    else:
        nutrition_panel = {
            "status": "TEMPLATE_ONLY",
            "note": "Structure only (serving size, RDA%, layout) — upload a NABL lab report to see real values. Numbers are never estimated from your entered figures.",
        }
        claims = {
            "status": "NOT_CHECKED",
            "checks": [],
            "note": "Claims validation requires an uploaded NABL lab report to back any claim — none was provided.",
        }

    all_checks = composition + micro + label
    overall = _aggregate_status(all_checks)

    violations = [
        {
            "severity": c["severity"],
            "status": c["status"],
            "message": f"{c['label']}: {c['actual']} (expected {c['expected']})",
            "ref": c["ref"],
        }
        for c in all_checks
        # Matches validation.js's violations filter exactly (every MISSING
        # check is a violation worth listing, not just CRITICAL ones) —
        # part of the same aggregate/section-status parity fix above.
        if c["status"] in ("FAIL", "WARNING", "MISSING")
    ]
    violations.sort(key=lambda v: SEVERITY_ORDER.get(v["severity"], 9))

    # Fix per review item C17: a category without a compiled microbiology
    # panel gets an explicit "NOT_AVAILABLE" section status instead of
    # _section_status([])'s default "PASS" — mirrors validation.js.
    extra_notes = []
    if category_id == "cheese":
        extra_notes.append(CHEESE_COMMON_RULE)
    if not micro_available:
        extra_notes.append(
            "Microbiology limits for this category haven't been compiled into Inspeckt yet — this report "
            "covers composition and labelling only. Verify microbiology separately against FSSAI's Appendix B "
            "before release."
        )

    return {
        "category": category_id,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "overall_status": overall,
        "composition": {"status": _section_status(composition), "checks": composition},
        "microbiological": (
            {"status": _section_status(micro), "checks": micro}
            if micro_available
            else {"status": "NOT_AVAILABLE", "checks": [], "note": "Microbiology limits for this category haven't been compiled into Inspeckt yet."}
        ),
        "labelling": {"status": _section_status(label), "checks": label},
        "nutrition_panel": nutrition_panel,
        "claims": claims,
        "shelf_life": shelf_life,
        "violations": violations,
        "disclaimer": REPORT_DISCLAIMER,
        "extra_notes": extra_notes,
    }
